### ISSUE TITLE
Request: TgSmush For Star Wars Racer

### ISSUE THREAD

**Issue by Netizen-King** [JeremyAnsel/xwa_TgSmush#2]
**Request:**

_A variant of your custom **TgSmush for [Star Wars Episode 1 Racer](https://www.gog.com/game/star_wars_episode_i_racer)** which will allow us to call on our custom HD video files._

**Background:**

JayFoxRocks of the [Open Star Wars Episode 1 Racer](https://github.com/JayFoxRox/openswe1r) modding community suggested reaching out to you. So I am creating a ticket in hopes that you might be able to look into this issue since you have so much experience with LucasArts Smush files and creating your custom player.

I started experimenting with your custom TgSmush.dll with SWE1R.

The thought was that is might just work if the SWE1R exe could read the dll.

I renamed the TgSmush.dll to Smush.dll as is required by the exe (along with the config file and I renamed the original smush to the name given in the readme) but I was returned errors.

"The ordinal 5 could not be located in the DLL"

It was suggested to me by JayFoxRocks that if a .def file was added to the package so that the TgSmush has ordinals, it might work.

I would be willing to supply you with a copy of the game for you to test if you would be willing to look into this issue.

Best Regards

**Comment by JeremyAnsel** [comment]
Hello,

The function `SmushGetFrameCount` is not present in `Smush.dll`.
To use `Smush.dll` instead of `TgSmush.dll`, you have to rename `TgSmush` to `Smush` where the name appears.

The first step is to generate the import library for `SmushOrig.dll`. To do that, follow the instructions in `make_import_lib.txt`. Then edit `SmushOrig.h` to remove `SmushOrigGetFrameCount`.

The second step is to update `Smush.dll`. In `smush.cpp`, update the links to the `SmushOrig` header and lib.
You may have to check the parameters of the `SmushOrigPlay` and `SmushPlay` functions.

The next step is to edit `dshow.player.cpp` to update the addresses of variables in the `DShowPlayVideo` function.

**Comment by Netizen-King** [comment]
Thank you for your response, Jeremy.

I have done the steps outlined in your readme file for TgSmush which include renaming. This is where I came across the error regarding "ordinal 5".

I am not knowledgeable in coding/compiling unfortunately.

I hope that you might find some interest in helping this project.

My skill set is primarily in video production and I have created HD cutscenes for SWE1R. 

I was able to pull the video out of the compressed smush files but was not able to encode the video files back in since there was not a publicly available smush encoder. 

This is when I came across your custom video player .dll for X-Wing Alliance upgrade.

Would you be willing to make this work for Star Wars Episode 1 Racer like you did for XWAU?

I would be happy to provide you with a copy of the game for your testing purposes if you can help us!

**Comment by JeremyAnsel** [comment]
Hello,

Here is a custom `Smush.dll` to test:

[Smush.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3269832/Smush.zip)

**Comment by Netizen-King** [comment]
Thank you for help me with this.

I have tested with both "test1" and "test2" but when the intro video comes, the game crashes back to Windows 10 desktop. 

Will the video directory be the same?

The files are stored in:

**STAR WARS Racer/data/anims**

Also, will the new Smush.dll open just .avi files or will it also open .mp4? (I am testing using avi since this is what it appears to support)

**Comment by JeremyAnsel** [comment]
[Test3.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3269867/Test3.zip)

The new dll opens avi and wmv files. It doesn't open mp4 files.

**Comment by JeremyAnsel** [comment]
The code uses these vatiables:
```cpp
HWND srcWindow = *(HWND*)0xDFA9F8;
LPDIRECTDRAW srcDirectDraw = *(LPDIRECTDRAW*)0x52D424;
int& srcUserInterrupted = *(int*)0x50B58C;

// Free DirectDraw resources
((void(*)())0x489970)();

// Init DirectDraw resources
((void(*)(HWND))0x489760)(srcWindow);
```

**Comment by Netizen-King** [comment]
It partially works!

The game engine flashes to the desktop for a few seconds then the video loads. 

While the video had loaded, it is non skippable (is this normal behaviour?).

Once the video is done playing, the main menu doesn't load properly.

I've made a short video for you to review it's behaviour: https://www.youtube.com/watch?v=YIwTQvDFq5s

**Comment by JeremyAnsel** [comment]
Can you attach the game exe : `SWEP1RCR.EXE`

**Comment by Netizen-King** [comment]
There are 2 versions, the original and a `-patched` variant which included HD font support and some netplay patches from the Open SWE1R project.

here it is: https://drive.google.com/open?id=1meoId-RXqGlWovcVwlYsFCL19OQR5WeT

**Comment by JeremyAnsel** [comment]
Thanks

**Comment by Netizen-King** [comment]
Thank you!

**Comment by JeremyAnsel** [comment]
[Test4.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3272249/Test4.zip)

You can skip video playing by pressing Escape, Space, Return, Back, or by clicking.

**Comment by Netizen-King** [comment]
Test4 does not work. It will load the first 2 animations (original) then the exe crashes when it tried to load the custom .avi

**Comment by JeremyAnsel** [comment]
Can you share a custom avi?

**Comment by Netizen-King** [comment]
No, I cannot - it is way too large in size to share (54GB). All .avi files I render seem to be very large in size. And when I try to make them smaller, the quality loss is substantial.

I usually render .mp4 for all of my videos due to it's space efficiency and high quality. 

I'm not used to rendering in .avi and I'm not sure why they are so large. 

The exact same video rendered as a h.264 .mp4 file is only 141MB. 

This is something I need to figure out on my end of course. But ideally as a modpack for sharing video files .mp4 would be a better option if you were able to implement this.

I've tried rendering in .wmv but the loss in quality is also substantial compared to .mp4.

If you have any suggestions, I would be happy to try.

**Comment by JeremyAnsel** [comment]
[Test5.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3273316/Test5.zip)

I was not testing with the right version, so it leaded to a crash.
```cpp
HWND srcWindow = *(HWND*)0xDFAA28;
LPDIRECTDRAW srcDirectDraw = *(LPDIRECTDRAW*)0x52D454;
```
It seems that your avi files are not compressed.

**Comment by Netizen-King** [comment]
I know it sounds crazy, but this 54GB avi was actually created using Adobe's compressed avi format in Adobe Media Encoder (not uncompressed). I don't understand why it's so large. It took 45min to render the 2 min. clip. 

Is there an open source .mp4 library that could be used for the player to add .mp4 functionality? 

Test5 does load the avi file. However, before it loads, the desktop is seen for a few seconds. 

Is this normal behaviour?

**Comment by Netizen-King** [comment]
I'm sure you know much more about this than I do, but I was doing research trying to find an MPEG-4 player in C++.

I dug into [Handbrake](https://github.com/HandBrake) curious about what it uses but I couldn't find the exact description on it's page. Perhaps it's part of an additional library that needs to be downloaded before compiling.

I also found [this](https://github.com/DicomJ/mpeg-isobase) - Is this relevant for adding mp4 support to your custom player?

If MP4 support can be incorporated, then the video download package for X-Wing Alliance upgrade and the HD Racer videos can both be set at extremely high quality with a very little digital footprint (small size).

I will also work on recording a video to show you the desktop flashing if you'd like.

**Comment by JeremyAnsel** [comment]
[Test6.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3293361/Test6.zip)

Hello,
I've added support for mp4 files using Media Foundation.

**Comment by Netizen-King** [comment]
Hi Jeremy, 

This is very good but there are a few issues.

Test6 plays .mp4 but the .exe crashes once the video is done playing.

Also, can you implement skip buttons for keyboard (and possibly controller?) in upcoming versions like you have in the original .dll so we can skip past the .mp4?

If there's anything else I can provide you with, please let me know! 

I appreciate all of your work

**Comment by JeremyAnsel** [comment]
[Test7.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3293427/Test7.zip)

I've fixed the keyboard input.

**Comment by Netizen-King** [comment]
I can confirm that the keyboard input works.

The exe still crashes after the video plays.

**Comment by JeremyAnsel** [comment]
Can you attach an error report from the event viewer?

**Comment by Netizen-King** [comment]
Yes I think so. Is this what you would like? [log image from event viewer](https://imgur.com/v4rrzHj)

**Comment by JeremyAnsel** [comment]
Yes, that's what I meant.

[Test8.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3294509/Test8.zip)

I've fixed a bug. May be not related to the crash.

**Comment by Netizen-King** [comment]
It didn't play the video this time and the exe crashed. 

[Event Viewer](https://imgur.com/a/kHyC6dq)

**Comment by JeremyAnsel** [comment]
[Test9.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3298048/Test9.zip)

The video is played fine on my computer and the game doesn't crash.
I'm running the game on Windows 10 with dgVoodoo.

Is there a difference between playing an avi file or a mp4 file?

**Comment by Netizen-King** [comment]
Yes, there is a difference between playing an avi or mp4.

Originally, I did not have an .avi in the video directory (this was removed after your introduced mp4 support). 

With only the original `IntroScene.znm` and my custom `IntroScene.mp4`, the .exe crashes.

If I add the avi back to the video directory, `IntroScene.avi` still does not play with Test9.

Test9 also does not default to the original `IntroScene.snm` as a fall back when it cannot play the custom video.

However, with the `IntroScene.avi` in the directory, `SWEP1RCR.exe` does not crash and it does successfully reach the main menu.

I am also running the game in GOG on Windows 10.

Are you also running the GOG version? What other information I can give to you?

**Comment by JeremyAnsel** [comment]
I am running the CD version.

I can reproduce the issue where the video is not played. When I replace the Goldie video with a mp4 file, the video is played. But when I replace the TextCrawl or IntroScene video, the video is not played.

**Comment by Netizen-King** [comment]
I can confirm that if I add a Goldie.mp4 the player does load the video. But once I try to skip the video, the exe crashes.

This is interesting that the Goldie video will play but still results in a crash, whereas if the same video is named IntroScene.mp4, the video does not play at all and there is still a crash.

When you are able to get the video to play, are you also able to reach the main menu or is there also an exe crash for you?

**Comment by JeremyAnsel** [comment]
[Test10.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3298709/Test10.zip)

Now, I can play the video fine.
There is no crash for me. The main menu appears.

**Comment by Netizen-King** [comment]
For IntroScene: 

It plays for .mp4 but before the main menu crashes if I try to skip it or if I let it play out without hitting any buttons. 

It plays the .avi and will reach the main menu when I hit a button to skip.

And if neither .avi or .mp4 are found, the player will default properly to the original .snm file.

So it appears to be an issue with the mp4 playback on my end still. 

But it seems that you are very close.

**Comment by JeremyAnsel** [comment]
[Test11.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3301796/Test11.zip)

I've updated the mp4 player shutdown function.
I've not modified the avi player.

**Comment by Netizen-King** [comment]
.snm support = works
.avi support = works

.mp4 support = plays IntroScene video but will crash on video skip or video completion

I also tested using the Goldie video and the same thing happens, the video plays but will crash on completion or trying to skip

**Comment by JeremyAnsel** [comment]
[Test12.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3302933/Test12.zip)

I've succeeded to reproduce a crash that happens after a video is played. I've fixed it.

**Comment by Netizen-King** [comment]
I'm still experiencing the same crashes. 

.mp4 support = plays IntroScene video but will crash on video skip or video completion

Here is the event viewer log: https://imgur.com/5b087A2

Is there any other information that might help you that I can supply?

**Comment by JeremyAnsel** [comment]
[Test13_debug.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3303016/Test13_debug.zip)

Can you try this debug version?
Use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to see if an error message appears.

**Comment by Netizen-King** [comment]
I ran this ad admin during the crash but nothing comes up in the DebugView window unless I turn on kernel monitoring.

These came up but do not appear to be related to my activity in SWE1R

https://imgur.com/vHshLvs

All of the capture settings are turned on except for Kernel. 

The mp4 doesn't play and the exe crashes.

Are there specific settings I must use?

**Comment by JeremyAnsel** [comment]
No specific setting. Just run it as a regular user. It is not required to run it as admin.

**Comment by Netizen-King** [comment]
Nothing comes up when I run the exe

**Comment by Netizen-King** [comment]
Do you know of another debugging software I could try?

**Comment by JeremyAnsel** [comment]
[Test14.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3303117/Test14.zip)

I've added a few log messages.

It should show Something like that:
```
[2948] begin MFPlayVideo
[2948] before PlayVideo: C:\Program Files (x86)\LucasArts\RACER\.\data\anims\IntroScene.mp4
[2948] instance initialized
[2948] url opened
[2948] video interrupted by keyboard
[2948] end of message loop
[2948] after PlayVideo: 1
[2948] end MFPlayVideo
```

**Comment by Netizen-King** [comment]
This version was able to be picked up by DebugView. 

The exe loaded the .mp4 when when I hit a key to skip, it crashed.

Here is the output: https://imgur.com/NXxqr81

**Comment by JeremyAnsel** [comment]
Does it crash when you play the whole video until the end?

**Comment by Netizen-King** [comment]
Yes it crashes whether I skip the video or let it play until the end. 

The output of DebugView: https://imgur.com/3XwEURx

**Comment by JeremyAnsel** [comment]
[Test15.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3303274/Test15.zip)

**Comment by Netizen-King** [comment]
Same thing as last time.

#17-24 = skipping mp4

#25-32 = letting mp4 play to completion

Both cases end with an exe crash: https://imgur.com/kbkz4A8

**Comment by JeremyAnsel** [comment]
[Test16.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3304457/Test16.zip)

It should show:
```
[5716] SmushStartup
[5716] SmushSetVolume
[5716] SmushPlay: C:\Program Files (x86)\LucasArts\RACER\.\data\anims\Goldie.znm
[5716] SmushShutdown
[5716] SmushStartup
[5716] SmushSetVolume
[5716] SmushPlay: C:\Program Files (x86)\LucasArts\RACER\.\data\anims\TextCrawl.znm
[5716] SmushShutdown
[5716] SmushStartup
[5716] SmushSetVolume
[5716] SmushPlay: C:\Program Files (x86)\LucasArts\RACER\.\data\anims\IntroScene.znm
[5716] begin MFPlayVideo
[5716] before PlayVideo: C:\Program Files (x86)\LucasArts\RACER\.\data\anims\IntroScene.mp4
[5716] instance initialized
[5716] url opened
[5716] video interrupted by keyboard
[5716] end of message loop
[5716] after PlayVideo: 1
[5716] end MFPlayVideo
[5716] SmushShutdown
```

**Comment by Netizen-King** [comment]
I do see this in DebugView for Test16.

It plays the IntroScene.mp4 but then crashes the exe on skip: https://imgur.com/jNli9Vy

**Comment by Netizen-King** [comment]
Are you still not experiencing any crashes? Could there be some difference in the GOG and PC version that we're not accounting for?

**Comment by JeremyAnsel** [comment]
Interesting, the last "SmushShutdown" message doesn't show up.

[Test17.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3307499/Test17.zip)

I use the exe you attached.

**Comment by Netizen-King** [comment]
_This one works 100%_ 

I've tested all 3 video types. I've changed the custom video to Goldie as well as PlanetA and it all works.

_Congrats and good work!_

**I only have 1 more request:**

_Can you implement controller support by adding the **"Start" and "A", "B", "X" and "Y"** to the function for skipping the video?_

Many people will play this game with a controller in front of a TV on the couch using something like the Steam Link or a home theater Gaming PC connected to their TV.

In these cases, they would not have a keyboard attached and would be reliant on their controllers.

Without this support, they would have to sit through all of the cutscenes. 

It would also server to compliment the original video player which also has controller support.

_Would this information help you?_ https://docs.microsoft.com/en-us/windows/uwp/gaming/registry-data-for-game-controllers

**Comment by JeremyAnsel** [comment]
[Test18.zip](https://github.com/JeremyAnsel/xwa_TgSmush/files/3314335/Test18.zip)

I've added joystick skipping by any button.

**Comment by Netizen-King** [comment]
That's amazing,  @JeremyAnsel ! Thanks so much for all of your hard work on this. 

As far as I can tell, everything is in working order but if I have any troubles with any other video content, I'll reach out to you.

I'm going to keep working on the videos and if I can figure out how to extract the textures (in .bin files) I'll also get to making HD textures for the game as well.

If you would like to keep in contact to see how the project is going, I have set up a discord server for the project: [SWE1R HD Upgrade Pack](https://discord.gg/Pn9yEcK)

I have a credits page there with your name on it and once the modpack is complete I will put you in the credits there as well along with your Github page if you'd like.

You can also email me at: Jeremy.R.J.King (at) gmail.com

**Comment by JeremyAnsel** [comment]
Hello,
I've joined the Discord server. My pseudo is JeremyaFr.

**Comment by JeremyAnsel** [comment]
Hello,
I've uploaded the source code at [swe1r_Smush](https://github.com/JeremyAnsel/swe1r_Smush).
Download link: [Smush.zip](https://raw.githubusercontent.com/JeremyAnsel/swe1r_Smush/master/Smush2/zip/Smush.zip).

**Comment by Netizen-King** [comment]
Hi, Jeremy. I hope you are well!

I am wondering if you would be available to help me with squashing a few
bugs users are experiencing in the SWE1R Smush dll?

I opened an issue in April. I'm not sure if this is proper etiquette:
https://github.com/JeremyAnsel/swe1r_Smush/issues/1

These are uncertain times and I understand if you are not able to do this
right now but I wanted to bring it to your attention in case you were able
to work on it.

Thanks!

- Jeremy King
